---
title: "ADDDM - Case Study 1"
author: "Francisco Arrieta - Jonathan Edwards"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(data.table)
library(ggplot2)
```

# Data Exploration

HELLO HELLO THIS IS JONATHAN PUSH TEST

ANOTHER TEST

```{r Import Data}
sol_panels <- fread("Case_Stud_I.csv", sep = ",", header = T)

print("test")

attach(sol_panels)
plot(number_of_solar_panels, manufacturing_cost, title ="Scatter plot of mean cost per unit")
detach(sol_panels)

exp_curve <- ggplot(data = sol_panels, aes(x= number_of_solar_panels, y = manufacturing_cost)) +
  geom_line(color = "#0099F8")+
  labs(title = "Bevaviour of mean cost per unit of production", x= "Production Amount", y = "Manufacturing Cost")+
  theme(plot.title = element_text(color = "#0099F8", size = 12, face = "bold"))

exp_curve
```

```{r}
exp_curve_log <- ggplot(data = sol_panels, aes(x= log(number_of_solar_panels), y = log(manufacturing_cost))) +
  geom_line() +
  stat_smooth(method = "lm")
exp_curve_log

```

```{r}
predict = lm(log(manufacturing_cost) ~log(number_of_solar_panels), data = sol_panels)
plot(predict)

summary(predict)

```

$C_{x} &= C_{1}x^{\log_{2}(b)}$

$$\begin{aligned} b
&= \log_{2}(\tilde b)\\
&= \frac{\log{(\tilde b)}}{\log(2)\\
}
\end{aligned}$$

$ $

```{r}
predict$coefficients

lr = 2^predict$coefficients[2]
lr
1-lr
learn_rate = 1 - exp(log(2)*predict$coefficients[2])

print(learn_rate)
```

```{r}
# set A and B

A <- predict$coefficients[1]
A <- as.numeric(exp(A))
print(A)

B <- as.numeric(predict$coefficients[2])
print(B)

pred_cost_table <- data.frame("Production_Amount" = seq(100, 5000, 100))

pred_cost_table["Pred_Cost"] <- (pred_cost_table$Production_Amount ^ B)*A

mean_cost <- mean(pred_cost_table[47:50, "Pred_Cost"])
mean_cost
```

```{r}
pred_cost_plot <- ggplot() +
  geom_point(data = sol_panels, aes(x= number_of_solar_panels, y = manufacturing_cost)) +
  geom_line(data = pred_cost_table, aes(x= Production_Amount, y = Pred_Cost, color = "red"))
pred_cost_plot

pred_sd <- sd(sol_panels$manufacturing_cost)

pred_cost_table["Lower_Bound"] <- pred_cost_table$Pred_Cost - pred_sd * 1.96
pred_cost_table["Upper_Bound"] <- pred_cost_table$Pred_Cost + pred_sd * 1.96



pred_cost_plot_CI <- ggplot(data = pred_cost_table) +
  geom_line(aes(x= Production_Amount, y = Pred_Cost, color = "red"))+
  geom_line(aes(x= Production_Amount, y = Upper_Bound, color = "blue"))+
  geom_line(aes(x= Production_Amount, y = Lower_Bound, color = "blue"))

pred_cost_plot_CI
```

```{r}
CI = confint(predict)
CI

b_upper = CI[2,2]
b_lower = CI [2,1]


pred_cost_table["Lower_Bound"] <- A*(pred_cost_table$Production_Amount^b_upper)
pred_cost_table["Upper_Bound"] <- A*(pred_cost_table$Production_Amount^b_lower)

```

log-log graph to behave in a linear way
